/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "stencil-hotfix/internal";
export namespace Components {
    interface HelloWorld {
    }
}
declare global {
    interface HTMLHelloWorldElement extends Components.HelloWorld, HTMLStencilElement {
    }
    var HTMLHelloWorldElement: {
        prototype: HTMLHelloWorldElement;
        new (): HTMLHelloWorldElement;
    };
    interface HTMLElementTagNameMap {
        "hello-world": HTMLHelloWorldElement;
    }
}
declare namespace LocalJSX {
    interface HelloWorld {
    }
    interface IntrinsicElements {
        "hello-world": HelloWorld;
    }
}
export { LocalJSX as JSX };
declare module "stencil-hotfix" {
    export namespace JSX {
        interface IntrinsicElements {
            "hello-world": LocalJSX.HelloWorld & JSXBase.HTMLAttributes<HTMLHelloWorldElement>;
        }
    }
}
