export const STENCIL_CORE_ID = 'stencil-hotfix';
export const STENCIL_INTERNAL_ID = 'stencil-hotfix/internal';
export const STENCIL_APP_DATA_ID = 'stencil-hotfix/internal/app-data';
export const STENCIL_APP_GLOBALS_ID = 'stencil-hotfix/internal/app-globals';
export const STENCIL_HYDRATE_FACTORY_ID = 'stencil-hotfix/hydrate-factory';
export const STENCIL_INTERNAL_CLIENT_ID = 'stencil-hotfix/internal/client';
export const STENCIL_INTERNAL_CLIENT_PATCH_BROWSER_ID = 'stencil-hotfix/internal/client/patch-browser';
export const STENCIL_INTERNAL_CLIENT_PATCH_ESM_ID = 'stencil-hotfix/internal/client/patch-esm';
export const STENCIL_INTERNAL_HYDRATE_ID = 'stencil-hotfix/internal/hydrate';
export const STENCIL_MOCK_DOC_ID = 'stencil-hotfix/mock-doc';
export const APP_DATA_CONDITIONAL = '?app-data=conditional';
export const LAZY_BROWSER_ENTRY_ID = '@lazy-browser-entrypoint' + APP_DATA_CONDITIONAL;
export const LAZY_EXTERNAL_ENTRY_ID = '@lazy-external-entrypoint' + APP_DATA_CONDITIONAL;
export const USER_INDEX_ENTRY_ID = '@user-index-entrypoint';
